// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SecureNfc.Data;

#nullable disable

namespace SecureNfc.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827130414_CreatedAllTheModels")]
    partial class CreatedAllTheModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SecureNfc.Data.Models.V1.V1Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EntityCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaintenanceStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EntityCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("SecureNfc.Data.Models.V1.V1Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("SecureNfc.Data.Models.V1.V1Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssetId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<byte>>("Signature")
                        .IsRequired()
                        .HasColumnType("smallint[]");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Tags", t =>
                        {
                            t.HasCheckConstraint("CK_Tag_OnlyOneOwner", "NOT (\"AssetId\" IS NOT NULL AND \"UserId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SecureNfc.Data.Models.V1.V1User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EntityCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SecureNfc.Data.Models.V1.V1Asset", b =>
                {
                    b.HasOne("SecureNfc.Data.Models.V1.V1User", "User")
                        .WithMany("Assets")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecureNfc.Data.Models.V1.V1Log", b =>
                {
                    b.HasOne("SecureNfc.Data.Models.V1.V1Asset", "Asset")
                        .WithMany("Logs")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecureNfc.Data.Models.V1.V1User", "User")
                        .WithMany("AssetLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecureNfc.Data.Models.V1.V1Tag", b =>
                {
                    b.HasOne("SecureNfc.Data.Models.V1.V1Asset", "Asset")
                        .WithOne("Tag")
                        .HasForeignKey("SecureNfc.Data.Models.V1.V1Tag", "AssetId");

                    b.HasOne("SecureNfc.Data.Models.V1.V1User", "User")
                        .WithOne("Tag")
                        .HasForeignKey("SecureNfc.Data.Models.V1.V1Tag", "UserId");

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecureNfc.Data.Models.V1.V1Asset", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SecureNfc.Data.Models.V1.V1User", b =>
                {
                    b.Navigation("AssetLogs");

                    b.Navigation("Assets");

                    b.Navigation("Tag");
                });
#pragma warning restore 612, 618
        }
    }
}
